1. Python program to convert a list of numeric value into a one-dimensional
NumPy array

In [2]:
import numpy as np
l = [12.23, 13.32, 100, 36.32]
a = np.array(l)
print(a)

[ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10

In [3]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11

In [20]:
import numpy as np
x = np.zeros(10)
x[6] = 11
print(x)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last)

In [21]:
import numpy as np
x = np.arange(5, 11)
x = x[::-1]
print(x)

[10  9  8  7  6  5]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [22]:
import numpy as np
x = np.ones((5,5))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.

In [23]:
import numpy as np
x = np.ones((3,3))
x = np.pad(x, pad_width=1, constant_values=0)
print(x)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [24]:
import numpy as np
x = np.zeros((8,8),dtype=int)
x[::2, ::2]=1
x[1::2, 1::2]=1
print(x)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


8. Write a Python program to convert a list and tuple into arrays.

In [17]:
import numpy as np
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("list", my_list)
print("List to array: ")
print(np.array(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.array(my_tuple))

list [1, 2, 3, 4, 5, 6, 7, 8]
List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array.

In [ ]:
import numpy as np
arr1 = np.array([10, 20, 30])
print("Original array: ", arr1)
arr2 = np.array([40, 50, 60, 70, 80, 90])
new_arr=np.append(arr1, arr2)
print(new_arr)

Original array:  [10 20 30]
[10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers

In [20]:
import numpy as np
x = np.sqrt([1+0j, 0+1j])
print("Original array: ",x)
print("Real part:")
print(x.real)
print("Imaginary part:")
print(x.imag)

Original array:  [1.        +0.j         0.70710678+0.70710678j]
Real part:
[1.         0.70710678]
Imaginary part:
[0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements

In [ ]:
import numpy as np
x = np.array([1,2,3], dtype=np.float16)
print("Size of the array: ", x.size)
print("Length of one array element in bytes: ", x.itemsize)
print("Total bytes consumed by the elements of the array: ", x.nbytes)

Size of the array:  3
Length of one array element in bytes:  2
Total bytes consumed by the elements of the array:  6


12. Write a Python program to find common values between two arrays.


In [22]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Common values between two arrays:
[10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.


In [23]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = [10, 30, 40, 50, 70]
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

Unique values in array1 that are not in array2:
[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.

In [24]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = [10, 30, 40, 50, 70]
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.

In [ ]:
import numpy as np
a = np.array([1, 2])
b = np.array([4, 5])
print("Array a: ",a)
print("Array b: ",b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))

Array a:  [1 2]
Array b:  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


15. Write a Python program to save a NumPy array to a text file.

In [19]:
import numpy as np
import os
x = np.arange(12).reshape(4, 3)
hd = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=hd) 
result = np.loadtxt('temp.txt')
print(result)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


16. Write a Python program to create a contiguous flattened array.

In [18]:
import numpy as np
x = np.array([[10, 20, 30], [20, 40, 50]])
y = np.ravel(x)
print(y)

[10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.

In [4]:
import numpy as np
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
print(x.dtype)
y = x.astype("float32")
print(y)
print(y.dtype)

[[ 2  4  6]
 [ 6  8 10]]
int32
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
float32


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros

In [ ]:
import numpy as np
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]

In [ ]:
import numpy as np
x = np.tri(4, 3, -1)
print(x)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.

In [7]:
import numpy as np
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])
c = np.concatenate((a, b), 1)
print(c)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only).


In [9]:
import numpy as np
a = np.zeros(11)
print(a)
a[1] = 2
print(a)
a.setflags(write=False)
a[1] = 7

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: assignment destination is read-only

22. Write a Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.

In [17]:
import numpy as np
a = np.arange(12).reshape(3, 4)
b = a * 3
print(b)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.


In [11]:
import numpy as np
x= np.arange(6).reshape(3, 2)
print(x)
print("Array to list:")
print(x.tolist())

[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


24. Write a NumPy program to display NumPy array elements of floating values with precision 3.

In [12]:
import numpy as np
x=np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,             
  0.35399976, 0.99469633, 0.0694458, 0.54711478]) 
np.set_printoptions(precision=3)
print(x)


[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.

In [13]:
import numpy as np
x=np.array([1.6e-10, 1.6, 1200, .235]) 
np.set_printoptions(suppress=True)
print(x)

[   0.       1.6   1200.       0.235]


26. Write a Python program to how to add an extra column to an numpy array.

In [15]:
import numpy as np
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])
print(np.append(x, y, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


27. Write a Python program to remove specific elements in a numpy array.

In [16]:
import numpy as np
x = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
index = [0, 3, 4]
new_x = np.delete(x, index)
print(new_x)

[ 20  30  60  70  80  90 100]
